### ISSUE TITLE
Strange file handle wiped block bin (This doesnt impact any current versions)

### ISSUE THREAD

**Issue by anarchy9388** [anarchy9388/scan#10]
lglf132:/tmp # ls -alhr /dae/uuid-02c90d81-4cd9-46c0-b11b-4e4fe51583ac/0039
-rw-rw-rw- 1 root root 0 Jul  8 14:05 /dae/uuid-02c90d81-4cd9-46c0-b11b-4e4fe51583ac/0039

**Comment by MarkHe1222** [comment]
from the detail of time, seems like it's modified by our script right?

**Comment by anarchy9388** [comment]
@MarkHe1222 
Yeah, when I was debugging the filehandle issue I did something weird with the filehandle and it wiped out that blockbin, made python crash and produce a core dump. But we don't need to worry about this, file handle is fixed in 0.2 branch so going to close this.
