### ISSUE TITLE
version 0.6 , it take lot of time when get free block from SS table when remove DTParser

### ISSUE THREAD

**Issue by MarkHe1222** [anarchy9388/scan#15]
**lglf131:/tmp/mark # python3 scan3.py scan -f chunkids
scan3.py v0.6                 Started 2019-07-15 06:58:25

Log file will be saved in: /tmp/scan_busy_blocks_2019-07-15-06-58-25.log
Result will be saved in dir: /tmp/block_scan_results
Traceback (most recent call last):
  File "scan3.py", line 501, in <module>
    scan_busy_blocks_from_disk.main()
  File "scan3.py", line 451, in main
    self.do_scan(chunk_ids, history, is_force)
  File "scan3.py", line 398, in do_scan
    output_file = self.get_free_blocks_with_history()
  File "scan3.py", line 199, in get_free_blocks_with_history
    body = items[1]
IndexError: list index out of range
**

**Comment by anarchy9388** [comment]
@MarkHe1222 Fixed in PR @ #18
