### ISSUE TITLE
Why the stream handler of logging could print the console,even I did set it? 

### ISSUE THREAD

**Issue by MarkHe1222** [anarchy9388/scan#2]
ecsn5:/tmp/mark # python scan.py scan -f chunkids
scan.py v0.1.0                 Started 2019-06-24 10:16:28

DEBUG:root:Get dtquery ip: 10.142.12.205
Log file will be saved in: /tmp/scan_busy_blocks.log.2019-06-24-10-16-28
INFO:root:Log file will be saved in: /tmp/scan_busy_blocks.log.2019-06-24-10-16-28
Result will be saved in dir: /tmp/block_scan_res
INFO:root:Target chunkIds: ['1b095ee9-c859-4f1c-8d98-bfb35f150add', '303ecf7d-70e8-4499-a0a3-d5062c2022af', '447d6b6c-d891-4f8b-97e4-13bf3b4e0bca', '4d61b934-511f-4728-826c-c69cad8c0d2a', 'a46dd186-2bb8-4af3-8f92-fd4e0ec7fcde']
INFO:root:Scan mode is force: False
Total: 14260 candidate blocks need to pre-check.

DEBUG:root:Pre-checking block: /dae/uuid-a9b662bc-47eb-4b4f-bcc6-035fb7bc9eec/0052
INFO:root:Found target chunkid: a46dd186-2bb8-4af3-8f92-fd4e0ec7fcde in block: /dae/uuid-a9b662bc-47eb-4b4f-bcc6-035fb7bc9eec/0052
DEBUG:root:Pre-checking block: /dae/uuid-b31c396e-c3f5-4d9c-9983-94f26e39c2bb/0358
DEBUG:root:Pre-checking block: /dae/uuid-17c24e28-5b89-42f3-ac84-ee09f4cdbb68/0539
DEBUG:root:Pre-checking block: /dae/uuid-17c24e28-5b89-42f3-ac84-ee09f4cdbb68/0286
INFO:root:Found target chunkid: 303ecf7d-70e8-4499-a0a3-d5062c2022af in block: /dae/uuid-17c24e28-5b89-42f3-ac84-ee09f4cdbb68/0286
INFO:root:Found target chunkid: 447d6b6c-d891-4f8b-97e4-13bf3b4e0bca in block: /dae/uuid-17c24e28-5b89-42f3-ac84-ee09f4cdbb68/0286
DEBUG:root:Pre-checking block: /dae/uuid-781a1494-7f6e-4699-a9aa-13d5c79c0009/0278
DEBUG:root:Pre-checking block: /dae/uuid-781a1494-7f6e-4699-a9aa-13d5c79c0009/0279
DEBUG:root:Pre-checking block: /dae/uuid-781a1494-7f6e-4699-a9aa-13d5c79c0009/0274
DEBUG:root:Pre-checking block: /dae/uuid-781a1494-7f6e-4699-a9aa-13d5c79c0009/0275
DEBUG:root:Pre-checking block: /dae/uuid-781a1494-7f6e-4699-a9aa-13d5c79c0009/0276
DEBUG:root:Pre-checking block: /dae/uuid-781a1494-7f6e-4699-a9aa-13d5c79c0009/0277
DEBUG:root:Pre-checking block: /dae/uuid-781a1494-7f6e-4699-a9aa-13d5c79c0009/0270
DEBUG:root:Pre-checking block: /dae/uuid-781a1494-7f6e-4699-a9aa-13d5c79c0009/0271
INFO:root:Found target chunkid: 4d61b934-511f-4728-826c-c69cad8c0d2a in block: /dae/uuid-781a1494-7f6e-4699-a9aa-13d5c79c0009/0271
DEBUG:root:Pre-checking block: /dae/uuid-781a1494-7f6e-4699-a9aa-13d5c79c0009/0272
DEBUG:root:Pre-checking block: /dae/uuid-781a1494-7f6e-4699-a9aa-13d5c79c0009/0273

**Comment by anarchy9388** [comment]
@MarkHe1222 
I added a few lines to log to stdout while working on the script, you can remove them if you don't like it that way.
`        # Log to stdout for debugging purposes
        #out_handler = logging.StreamHandler(sys.stdout)
        #logging.getLogger('').addHandler(out_handler)`

**Comment by MarkHe1222** [comment]
But are these lines of code not being annotated? Why is this also effective?

and I tried remove those codes , the log still keep printing on the console?

**Comment by MarkHe1222** [comment]
@anarchy9388  Could you take a look here?
