### ISSUE TITLE
Receiver process logic enhancement and critical service protection

### ISSUE THREAD

**Issue by MarkHe1222** [anarchy9388/scan#21]
def receiver(self):
        received = []
        while True:
            bb_file = receiver_conn.recv()
            if bb_file in received:
                continue
            if bb_file == "END":
                break
            received.append(bb_file)
            logging.debug('Received block_bin_file: {}'.format(bb_file))
            blocks = self.candidate_blocks[bb_file]
            i = 0
            procs = []
            for block in blocks:
                i = i + 1
                logging.debug('block tag: {}'.format(i))
                position = int(block['offset'])
                size = int(block['size'])
                partition = block['partition']
                block_bin = block['blockBin']
                block_file = '/dae/uuid-{}/{}'.format(block['partition'], block['blockBin'])
                block_file_handle = open(block_file, 'rb')
                process = multiprocessing.Process(target=self.__parse_candidate_block,
                                                  args=(block_file_handle, position, size,
                                                        partition, block_bin, block_file,))
                procs.append(process)
                process.start()

                # TODO - process.join() call will block all other threads/processes, need some type of workaround
                #  here maybe there is something better we can use since we are on python 3?
                # process.join()
            for proc in procs:
                proc.join()

            # received.append(bb_file)

**Comment by anarchy9388** [comment]
```
sudo ionice -p `pidof storageserver` -c 1
```

**Comment by anarchy9388** [comment]
@MarkHe1222 

I was wrong here:
```
            # TODO - process.join() call will block all other threads/processes, need some type of workaround
            #  here maybe there is something better we can use since we are on python 3?
```

And after the script took down customer node I found a way to limit its resources to keep critical services running and not impact customer. 
I'm testing it on lab with good success, will continue testing it more.
```
    @staticmethod
    def __nice_init():
        # Set os.nice priority for our processes so they don't hog resources from critical services
        os.nice(19)
        logging.info('Set nice priority to 19.')

        # Use ionice to give SS "best-effort" priority so it gets disk priority over this script
        # I originally tried to give it real-time priority but seemed like it made system load very high
        # TODO - maybe set back to real time?
        retval, output = subprocess.getstatusoutput('ionice -p `pidof storageserver` -c 2')
        if retval != 0:
            logging.error('Failed to set ionice to best-effort for StorageServer')
            exit(100)
        logging.info('Set ionice to realtime for StorageServer')

        # Use ionice to give our script "idle" priority so we don't impact customer
        retval, output = subprocess.getstatusoutput('ionice -p {} -c 3'.format(os.getpid()))
        if retval != 0:
            logging.error('Failed to set ionice to idle for scan3.py')
            exit(101)
        logging.info('Set ionice to idle for scan3.py')
```
