### ISSUE TITLE
New test version

### ISSUE THREAD

**Issue by MarkHe1222** [anarchy9388/scan#4]
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
"""
@copyright: Copyright (c) 2019 DellEMC
All Rights Reserved

This software is protected, without limitation, by copyright law
and international treaties. Use of this software and the intellectual property
contained therein is expressly limited to the terms and conditions of the
License Agreement under which it is provided by or on behalf of DellEMC.

@since: 2019/04/21
@authors: Mark He
@version: 0.1.0
@description: scan the busy block for target chunks from disk
@change:
          0.0.1   2019/04/21     Mark - scan logic and retire flow
          0.1.0   2019/06/18     Mark - improve the _do_scan

"""

import argparse
import timeit
import datetime
import commands
import time
import json
import os
import zlib
import traceback
import logging
import sys
import re
import subprocess
import __main__ as main

try:
    from thread import get_ident as _get_ident
except ImportError:
    from dummy_thread import get_ident as _get_ident

from collections import OrderedDict
from pprint import pprint
from multiprocessing import Process
from multiprocessing import Lock, Value
from multiprocessing.pool import ThreadPool
from logging.handlers import RotatingFileHandler

__version__ = '0.1.0'

def parse_dt_entry(entry, light=False):
    DTParserer = DTParser()
    return (DTParserer.parse_dt_entry(entry, light))

def extract_dt_entries(entriesfile=None, entriesText=None, outputfile=None, parse=False):
    DTParserer = DTParser()
    return (DTParserer.extract_dt_entries(entriesfile=entriesfile, entriesText=entriesText, outputfile=outputfile,
                                          parse=parse))

def extract_dt_entries_new(entriesfile=None, entriesText=None, outputfile=None, parse=False):
    DTParserer = DTParser()
    return (DTParserer.extract_dt_entries_new(entriesfile=entriesfile, entriesText=entriesText, outputfile=outputfile,
                                              parse=parse))

class DTParser():
    def __init__(self):
        self._sys_reg = re.compile(r'key: "(.*)".*alue: "(.*)"', re.S)
        self._user_reg = re.compile(r'key: "(.*)".*alue: "(.*)"', re.S)
        self._repo_reg = re.compile(r'chunkId: "(.*)"', re.S)
        self._entry_reg = re.compile(r'(.*?): "?(.*?)"?$', re.M)
        self._header_reg = re.compile(r'[\n]?(.*)$')

    def parse_dt_light(self, entry):

        '''

        :param entry:
        :return:
        '''

        '''schemaType OBJECT_TABLE_KEY objectId 00066a2f7618c42cbe8f5c83c7876a8830eeef7465b3d9ce5bc1192bd829bd64 type UPDATE sequence 0
            segment {
              segmentUMR {
                sysMd {
                  key: "acl2"
                  value: "CgwKBmNidXNlchICCAQgACgAMgZjYnVzZXJIAA=="
                }
                sysMd {
                  key: "createtime"
                  value: "1506519266341"
                }
                sysMd {
                  key: "ctype"
                  value: "application/octet-stream"
                }
                sysMd {
                  key: "is-hole-case"
                  value: "false"
                }
                sysMd {
                  key: "current-zone-is-owner"
                  value: "true"
                }
              }
            }

            or

            schemaType OBJECT_TABLE_KEY objectId 00066a2f7618c42cbe8f5c83c7876a8830eeef7465b3d9ce5bc1192bd829bd64 type COMPACTION_MARKER sequence 1
            lastIndexedSequence: 1
            versionHistoryDesc: 0
            nullVersionStartSequence: 1
            markerVersion: version22
            '''
        result = {}
        linelevel = 0
        sectiontext = ""
        levelname = ""
        cur_keyname = ""

        for line in entry.splitlines():
            # print "line: {}".format(line)
            # print "line: '{}'".format(line)
            if line.startswith("schemaType"):
                continue

            if "{" in line and not line.strip().startswith(
                    "textValue"):  # startswith is temp hack for certain entries that have embedded { } chars
                # Start of a new level in tree.
                linelevel += 1

                if linelevel == 1:  # We're hitting the first level in the passed data; extract all lines until the matching }.  Recurse parse the intermediate lines.  Extract the name from the line
                    lineparts = line.split("{")
                    levelname = lineparts[0].strip()
                    if len(lineparts) >= 2:
                        sectiontext = "{}\n".format(lineparts[1].strip())

                    continue

            if "}" in line and not line.strip().startswith(
                    "textValue"):  # startswith here is temp hack for certain entries that have embedded { } chars
                linelevel -= 1

                if linelevel == 0:  # The end of a top-level section.  Take the collected lines (including anything before the } on this line), and recurse
                    # print "recursing on {}".format(sectiontext)
                    lineparts = line.split("}")
                    sectiontext += "{}\n".format(lineparts[0].strip())

                    # recurse on sectiontext
                    # print "Recursing with text '{}'".format(sectiontext)

                    sectionresult = self.parse_dt_light(sectiontext)

                    # print("sectionresult: '{}'".format(sectionresult))

                    if levelname == "":
                        print("ERROR:  Could not get section name for section: '{}'".format(pformat(sectionresult)))

                    # print levelname

                    if levelname in result:
                        # for key,val in sectionresult.iteritems():
                        #    result[levelname][key]=val
                        if levelname in ('sysMd', 'headSysMd', 'userMd'):
                            for key, val in sectionresult.iteritems():
                                result[levelname][key] = val
                        else:
                            if isinstance(result[levelname], dict):
                                result[levelname] = [result[levelname]]
                            result[levelname].append(sectionresult)
                    else:
                        result[levelname] = sectionresult

                    # print "result: {}".format(result)

                    continue

            if linelevel > 0:  # We're currently adding lines to sectiontext, which we'll recurse-parse
                sectiontext += line + '\n'

                continue

            strippedline = line.strip()

            # print "strippedline: '{}'".format(strippedline)

            if strippedline.startswith("key:"):
                cur_keyname = strippedline.replace("key:", "").strip()
                if cur_keyname.startswith('"') and cur_keyname.endswith('"'):  # Strip out any surrounding quotes
                    cur_keyname = cur_keyname[1:]
                    cur_keyname = cur_keyname[:len(cur_keyname) - 1]

                # print "Found keyname: "+cur_keyname

                continue
            # else:
            #    cur_keyname=""

            if cur_keyname != "" and "alue:" in strippedline:  # Potentially a value line
                val_line = True
                if strippedline.startswith("value:"):
                    cur_valname = strippedline.replace("value:", "").strip()
                elif strippedline.startswith("textValue:"):
                    cur_valname = strippedline.replace("textValue:", "").strip()
                elif strippedline.startswith("binaryValue:"):
                    cur_valname = strippedline.replace("binaryValue:", "").strip()
                else:  # Was probably something in the contents of the line that we matched
                    val_line = False

                if val_line:
                    if cur_valname.startswith('"') and cur_valname.endswith('"'):  # Strip out any surrounding quotes
                        cur_valname = cur_valname[1:]
                        cur_valname = cur_valname[:len(cur_valname) - 1]

                    # print "Found valname: "+cur_valname

                    result[cur_keyname] = cur_valname
                    cur_keyname = ""
                    continue

            if ":" in strippedline:
                lineparts = strippedline.split(":")

                key = lineparts[0]
                value = strippedline[len(key) + 1:].strip()
                if value.startswith('"') and value.endswith('"'):  # Strip out any surrounding quotes
                    value = value[1:]
                    value = value[:len(value) - 1]

                if key in result.keys():
                    # If the key already is in the DT dict, ensure both the value already in the dict and the value
                    # we just found are lists
                    if not isinstance(value, list):
                        value = [value]
                    if not isinstance(result[key], list):
                        result[key] = [result[key]]

                    result[key].extend(value)

                else:
                    result[key] = value

                continue

            if strippedline:
                print("ERROR: Don't know what to do with the current line: '{}'").format(strippedline)

        return (result)

    def extract_dt_entries(self, entriesfile=None, entriesText=None, outputfile=None, parse=False):
        """
        Based on a stream of data (output from any number of sources, including various DT commands, files, etc), attempt to locate and extract DT entries.

        If any found, returns a List of strings.  No parsing of the DT entry is done here - simply identifies if any exist and breaks them into primitive, otherwise un-parsed entries that can then be parsed or handled in any way.

        :param entriesfile:
        :param entriesText:
        :type entriesText: str
        :param outputfile
        :return: list of entries (if any)
        """

        entries = []

        if entriesfile:
            f = open(entriesfile)
        elif entriesText:
            f = entriesText.splitlines()

        # with open(entriesfile) as f:

        entry = None
        linecount = 0

        for line in f:
            linecount += 1

            if entriesText:
                line += "\n"

            if "\r" in line:
                line = line.replace("\r", "")

            if linecount < 10:  # For the first several lines, attempt to strip off any HTML junk that might exist).  For performance. only do this on the first lines
                # line = re.sub('<[^>]*>', '', line)
                line = re.sub('<.*>', '', line)

            if line.startswith("schemaType"):  # Start of a new entry
                if entry:  # If we already have a cached entry, process and flush the old one
                    if parse:
                        entry = self.parse_dt_entry(entry, light=True)
                    entries.append(entry)
                entry = line

            else:  # Lines that don't start a new entry; "body" lines
                if entry:  # Only start adding if we've found the start of an entry
                    if line.strip().startswith("<"):  # Potentially HTML tags
                        # Attempt to identify and strip trailing HTML junk near the end of an output.  Need to be careful as the DT entry itself can contain HTML; so for now we assume HTML tags, if any, will start at the beginning of the line (may need to refine)
                        # line = re.sub('<[^>]*>', '', line)
                        line = re.sub('<.*>', '', line)
                    entry += line

        if entry:  # Flush last entry, if any
            if parse:
                entry = self.parse_dt_entry(entry, light=True)
            entries.append(entry)

        if entriesfile:
            f.close()

        return entries

    def extract_dt_entries_new(self, entriesfile=None, entriesText=None, outputfile=None, parse=False):
        """
        Based on a stream of data (output from any number of sources, including various DT commands, files, etc), attempt to locate and extract DT entries.

        If any found, returns a List of strings.  No parsing of the DT entry is done here - simply identifies if any exist and breaks them into primitive, otherwise un-parsed entries that can then be parsed or handled in any way.

        :param entriesfile:
        :param entriesText:
        :type entriesText: str
        :param outputfile
        :return: list of entries (if any)
        """

        entries = []

        if entriesfile:
            f = open(entriesfile)
        elif entriesText:
            f = entriesText.splitlines()

        # with open(entriesfile) as f:

        entry = None
        linecount = 0

        for line in f:
            linecount += 1

            if entriesText:
                line += "\n"

            if "\r" in line:
                line = line.replace("\r", "")

            if linecount < 10:  # For the first several lines, attempt to strip off any HTML junk that might exist).  For performance. only do this on the first lines
                # line = re.sub('<[^>]*>', '', line)
                line = re.sub('<.*>', '', line)

            if line.startswith("schemaType"):  # Start of a new entry
                if entry:  # If we already have a cached entry, process and flush the old one
                    if parse:
                        entry = self.parse_dt_entry(entry, light=True)
                    yield (entry)
                entry = line

            else:  # Lines that don't start a new entry; "body" lines
                if entry:  # Only start adding if we've found the start of an entry
                    if line.strip().startswith("<"):  # Potentially HTML tags
                        # Attempt to identify and strip trailing HTML junk near the end of an output.  Need to be careful as the DT entry itself can contain HTML; so for now we assume HTML tags, if any, will start at the beginning of the line (may need to refine)
                        # line = re.sub('<[^>]*>', '', line)
                        line = re.sub('<.*>', '', line)
                    entry += line

        if entry:  # Flush last entry, if any
            if parse:
                entry = self.parse_dt_entry(entry, light=True)
            yield (entry)

        if entriesfile:
            f.close()

    def parse_dt_entry(self, entry, light=False):
        """
        Given the text of a single DT entry, parse the contents into a python dict, which is returned

        Parse line-by-line, adding key/val pairs as properties in the overall struct.

        The contents of the top-level schemaType line are parsed into a "header" structure.
        The remaining contents are parsed into a "body" structure.

        As we hit a line with a "{" (nested values), we get the name of the substructure and recurse, parsing until we hit the next corresponding } entry.

        Special handling is given for nested entries with sysMd, userMd, and other labels (which appear to contain only a single value).

        For example, the following DT data:

        schemaType OBJECT_TABLE_KEY objectId 00003bff6e071d48e90c655a46a3ab3b486800180b3139029aebd7c2f1733797 type UPDATE sequence 0
        segment {
          segmentUMR {
            sysMd {
              key: "acl2"
              value: "Cg4KCG9ianVzZXIyEgIIBCAAKAAyCG9ianVzZXIySAA="
            }
            sysMd {
              key: "is-hole-case"
              value: "false"
            }
            reposUMRLocations {
              chunkId: "7fea72e8-f323-46b2-80bc-87d97d405270"
              offset: 10414168
              endOffset: 10415216
              rangeInfo {
                relativeOffset: 1000
                relativeEndOffset: 1000
              }
            }
          }
        }

        ...Should become:

        entry['header']['schemaType']=OBJECT_TABLE_KEY
        entry['header']['objectId']=00003bff6e071d48e90c655a46a3ab3b486800180b3139029aebd7c2f1733797
        entry['header']['type']=UPDATE
        entry['header']['sequence']=0
        entry['body']['segment']['segmentUMR']['acl2']=Cg4KCG9ianVzZXIyEgIIBCAAKAAyCG9ianVzZXIySAA=
        entry['body']['segment']['segmentUMR']['is-hole-case']=false
        entry['body']['segment']['segmentUMR']['reposUMRLocations']['chunkId']=7fea72e8-f323-46b2-80bc-87d97d405270
        entry['body']['segment']['segmentUMR']['reposUMRLocations']['offset']=10414168
        entry['body']['segment']['segmentUMR']['reposUMRLocations']['endOffset']=10415216
        entry['body']['segment']['segmentUMR']['reposUMRLocations']['rangeInfo']['relativeOffset']=1000
        entry['body']['segment']['segmentUMR']['reposUMRLocations']['rangeInfo']['relativeEndOffset']=1000

        light: bool - Temporary - if specified, use a lighter-weight parser.

        """

        # parse schemaType and other header info, which should be the first text block (delimited by newline) in the entry.  It's also possibly the ONLY line in the entry.

        result = OrderedDict()
        result['header'] = dict()

        lines = entry.strip().splitlines()
        if len(lines) < 1:
            print "ERROR: parse_dt_entry():  Does not appear to be a valid DT entry"
            exit(1)

        if "schemaType" in lines[0]:
            keyname = None
            for item in lines[0].split():
                if not keyname:
                    keyname = item
                else:
                    result['header'][keyname] = item
                    keyname = None
        if light:
            if len(result['header']) > 0:
                result['body'] = self.parse_dt_light(entry)
            else:
                result = self.parse_dt_light(entry)
            return (result)

        # print "not doing light"

        npobj = NestedParser(r'\{', r'\}')
        self.nped = npobj.parse(entry)

        result['body'] = self.list_to_dict(self.nped)

        if not result.get('header'):
            result = result['body']

        return result

    def str_to_dict(self, strobj, ret_dict=False, targetdict=None):
        """
        Take strings and create dictionary of them, based on self._entry_reg regex
        Input: string to process and either True to return or dictionary to merge results into (overwriting)
        Output: dictionary result or merge into existing dictionary
        """
        dictobj = {}

        for (key, value) in self._entry_reg.findall(strobj):
            dictobj[key.strip()] = value.strip()

        if ret_dict:
            return dictobj
        elif targetdict:
            targetdict.update(dictobj)

    def list_to_dict(self, listobj):
        """
        Take list and create dictionary, using GPB noun as key
        Input: list to process
        Output: dictionary result
        """
        temp_dict = {}
        temp_list = []

        # print "list_to_dict(): Parsing list: "
        # pprint(listobj)

        for num, item in enumerate(listobj):
            if isinstance(item, list):
                # Find key from end of last list item (is reliable for GPB)
                header = self._header_reg.search(listobj[num - 1]).group(1)
                header = header.strip()

                # print "header: "+(header)

                if header in ('sysMd', 'headSysMd', 'userMd'):
                    # Handle this specific regex case and add that key and value
                    # to temp_dict at this level (don't do recursive call again)
                    if header not in temp_dict:
                        temp_dict[header] = {}

                    # If value is a simple object, like:
                    # userMd {
                    #      key: "ownerUid"
                    #      textValue: "readwrite"
                    #    }
                    # .. Then parse with a regex and extract the quoted value after "key" and inside *alue: "{}"
                    if len(item) == 1:
                        found = self._user_reg.search(item[0])
                        if len(found.groups()) == 2:
                            key, value = found.group(1, 2)
                            temp_dict[header][key] = value
                    else:
                        # If value is a more complex object, like:
                        # userMd {
                        #  key: "keypoolPolicy"
                        #  textValue: "{  \"Version\": \"2012-10-17\",  \"Id\": \"Policy on readwrite1 for readonly\",  \"Statement\": [  {  \"Sid\": \"readonly read access\",  \"Effect\": \"Allow\",  \"Principal\": \"readonly\",  \"Action\": [\"s3:GetObject\"],  \"Resource\": [\"readwrite1/public/*\"]  }  ]}"
                        # }
                        # ...Then item[] split's second value will be the value we want to keep

                        cur_reg = re.compile(r'key: "(.*)".*alue: "', re.S)
                        found = cur_reg.search(item[0])
                        if len(found.groups()) == 1:
                            key = found.group(1)
                            temp_dict[header][key] = item[1]

                else:
                    # Then add header to counter
                    if 'count_' + header not in temp_dict:
                        temp_dict['count_' + header] = 1
                    else:
                        temp_dict['count_' + header] += 1
                    # Then retrieve that same header from counter and use that
                    # as key (header + counter) for dict

                    if temp_dict['count_' + header] == 1:
                        key = header
                        temp_dict[key] = self.list_to_dict(item)
                    else:
                        key = header
                        if temp_dict.get(key):
                            if not isinstance(temp_dict[key], list):
                                temp_dict[key] = [temp_dict[key]]
                            temp_dict[key].append(self.list_to_dict(item))

            else:
                # Get key/value and add to dict
                temp_entry = self.str_to_dict(item, True)
                print temp_entry

                # Make sure the key we're about to add is not already present. If so convert it into a list
                for key, value in temp_entry.items():
                    if key in temp_dict.keys():
                        # If the key already is in the DT dict, ensure both the value already in the dict and the value
                        # we just found are lists
                        if not isinstance(value, list):
                            value = [value]
                        if not isinstance(temp_dict[key], list):
                            temp_dict[key] = [temp_dict[key]]

                        temp_dict[key].extend(value)
                        temp_entry[key] = temp_dict[key]

                temp_dict.update(temp_entry)

        return temp_dict

class NestedParser(object):
    """
    Parser to allow regex matching of nested parenthesis or other separators.
        Borrowed from
        http://stackoverflow.com/questions/1099178/matching-nested-structures-with-regular-expressions-in-python .
        Alternative is to use pyparsing, but that would be an external dependency and NestedParser may be faster:
        http://gotoanswer.stanford.edu/?q=Python%3A+How+to+match+nested+parentheses+with+regex%3F .
    Input: field delimiters (optional, paranthesis is default), string for parse method
    Output: nested list with split on the delimiters
    """

    def __init__(self, left=r'\{', right=r'\}'):
        self.scanner = re.Scanner([
            (left, self.left),
            (right, self.right),
            (r"\s+", None),
            (".+?(?=(%s|%s|$))" % (right, left), self.other),
        ], re.S)
        self.result = ParseNode()
        self.current = self.result

    def parse(self, content):
        """
        parse method
        """

        # print "parse(): Starting with"
        # pprint(content)
        self.scanner.scan(content)
        return self.result

    def left(self, scanner, token):
        """
        method for lexicon's left definition
        """
        new = ParseNode(self.current)

        # print "left(): Appending"
        # pprint (new)
        # print "to"
        # pprint (self.current)

        self.current.append(new)
        self.current = new

        # print "left(): self.current now updated to"
        # pprint (self.current)

    def right(self, scanner, token):
        """
        method for lexicon's right definition
        """
        self.current = self.current.parent

    def other(self, scanner, token):
        """
        method for lexicon's other definition
        """
        self.current.append(token.strip())

class ParseNode(list):
    """
    Utility class to track found patterns in NestedParser
    """

    def __init__(self, parent=None):
        list.__init__(self)
        self.parent = parent

class ScanBusyBlocksFromDisk():
    def __init__(self, args):
        self.time_string = time.strftime("%Y-%m-%d-%H-%M-%S")
        self.log_file = '/tmp/scan_busy_blocks.log.{}'.format(self.time_string)
        self.logging_init()
        self.print_version()
        self.args = args
        self.agent_path = '/host/data/id.json'
        self.res_dir = '/tmp/block_scan_res'
        self.FNULL = open(os.devnull, 'w')

        self.chunkids = None
        self.dtquery_ip = self._get_dtquery_ip()
        self.total_counter = -1

        self.lock = Lock()

    def logging_init(self):
        handler = RotatingFileHandler(filename=self.log_file,
                                      mode='a',
                                      maxBytes=52428800,
                                      backupCount=5)
        formatter = logging.Formatter('%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s')
        handler.setFormatter(formatter)
        logging.getLogger('').setLevel(logging.DEBUG)
        logging.getLogger('').addHandler(handler)

    def print_version(self):
        version_string = '{} v{}'.format(os.path.basename(os.path.realpath(main.__file__)), __version__)
        time_string = "                 Started {}".format(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

        sys.stderr.write('{}{}\n\n'.format(version_string, time_string))

    def _get_dtquery_ip(self):
        cmd = "sudo netstat -ntpl | grep 9101|awk '{print $4}'|tail -1|sed 's/:9101//g'"
        ip = commands.getoutput(cmd)
        logging.debug("Get dtquery ip: {}".format(ip))
        return ip

    def _get_cos(self):
        # cmd = "curl -sL \"http://" + self.dtquery_ip + ":9101/stats/ssm/varraycapacity/\" | grep VarrayId | awk -F'[<|>]' '{print $3}' | tr -d '\"'"
        cmd = "curl -sL \"http://{}:9101/stats/ssm/varraycapacity/\" | grep VarrayId | awk -F'[<|>]' '{{print $3}}'".format(
            self.dtquery_ip)
        cos = commands.getoutput(cmd)
        logging.debug("GET cos: {}".format(cos))
        return cos

    def get_free_blocks_with_history(self):
        logging.info("Start to get the target free blocks.")
        device_id = self.dtquery_ip
        cmd_get_device = 'curl -sL "http://{}:9101/diagnostic/SS/1/DumpAllKeys/SSTABLE_KEY/?type=device" | grep schema | awk \'{{print $NF}}\''.format(
            self.dtquery_ip)
        logging.info("cmd-[get devices]: {}".format(cmd_get_device))
        device_ids = commands.getoutput(cmd_get_device).replace('\r', '').split('\n')
        logging.info("devices: {}".format(device_ids))

        if os.path.exists(self.agent_path):
            with open(self.agent_path) as f:
                file_ = f.read()
                agent_id = file_.split('"')[-2]
                if agent_id in device_ids:
                    device_id = agent_id
                    logging.debug(
                        "Device Id shows as UUID: {} related with IP: {}".format(device_id, self.dtquery_ip))

        outfile = '/tmp/free_blocks_with_history_{}_{}'.format(device_id, self.time_string)
        cmd_get_owner_dt = 'curl -sL "http://{}:9101/diagnostic/hash/{}"'.format(self.dtquery_ip, device_id)
        logging.info("cmd-[get owner DT]: {}".format(cmd_get_owner_dt))
        owner_dt = commands.getoutput(cmd_get_owner_dt).replace('\n', '').split(' ')[-1].split('_')[0]
        logging.info("Owner DT: {}".format(owner_dt))

        cos = self._get_cos().split(':')[-1]
        cmd_get_free_blocks = 'curl -sL "http://{}:9101/urn:storageos:OwnershipInfo:{}__SS_{}_128_1:/SSTABLE_KEY/?type=FREE_BLOCK&device={}&useStyle=raw&showvalue=gpb"' \
            .format(self.dtquery_ip, cos, owner_dt, device_id)

        logging.info("cmd-[get free blocks]: {}".format(cmd_get_free_blocks))
        entries_text = commands.getoutput(cmd_get_free_blocks)
        entries = extract_dt_entries(entriesText=entries_text, parse=True)
        try:
            with open(outfile, 'a+') as f:
                for entry in entries:
                    entry_info = {}
                    if 'chunkHistory' not in entry['body']:
                        continue
                    entry_info['device'] = entry['header']['device']
                    entry_info['partition'] = entry['header']['partition']
                    entry_info['blockBin'] = entry['header']['blockBin']
                    entry_info['offset'] = entry['header']['offset']
                    entry_info['size'] = entry['body']['size']
                    entry_info['chunkHistory'] = entry['body']['chunkHistory']

                    f.write('{}\n'.format(json.dumps(entry_info, separators=(',', ':'))))
        except Exception as e:
            logging.error(
                "Hit error: {} when parsed entries for free blocks, traceback: {}".format(e, traceback.format_exc()))
        logging.info("All free blocks record saved in: {}".format(outfile))
        return outfile

    def read_target_block(self, input_file, start_offset, data_length, is_hex_to_dec):
        logging.info('read_target_block: input_file: {}, start_offset: {}, data_length: {}, is_hex_to_dec: {}'.format(
            input_file, start_offset, data_length, is_hex_to_dec
        ))
        with open(input_file, 'rb') as f:
            f.seek(start_offset, 0)
            target_byte = f.read(data_length)
            if is_hex_to_dec:
                target_byte = int(target_byte.encode('hex'), 16)

            return target_byte

    def write_target_block(self, data_buffer, chunkid, partition, blockBin, offset, length):
        """
        result of target busy block
        name pattern: chunkid_partition_blockbin_offset_length
        :return:
        """
        logging.info('write_target_block: data_buffer: {}, chunkid: {}, partition: {}, blockbin: {}, offset: {}, length: {}'.format(
            str(data_buffer), str(chunkid), str(partition), str(blockBin), str(offset), str(length)
        ))
        outfile = '{}/{}_{}_{}_{}_{}'.format(self.res_dir, chunkid, partition, blockBin, offset, length)
        with open(outfile, 'w') as f:
            f.write(data_buffer)
            logging.info("Target write block saved in: {}".format(outfile))

    def __do_scan(self, f, position, size, partition, blockBin, block_file):
        write_block_header = 4
        write_block_checksum = 8
        write_block_epoch = 36
        max_write_block_length = 2236960
        end_position = position + size
        logging.debug('Thread-id-{} START __do_scan: file: {}, position: {}, size: {}, partition: {}, blockBin: {}, '.format(
            _get_ident(), block_file, position, size, partition, blockBin))

        while position < end_position:
            f.seek(position, 0)
            try:
                target_byte = f.read(max_write_block_length)
                data_block_length = int(target_byte[position:write_block_header].encode('hex'), 16)
                logging.debug("Thread-id-{} data block length: {}".format(_get_ident(), data_block_length))
            except ValueError:
                position += 1
                continue

            if data_block_length > (max_write_block_length - 48):
                logging.debug(
                    "Thread-id-{} No header matched length: {}, current position: {} jump to next byte.".format(
                        _get_ident(), position,
                        data_block_length))
                position = position + 1
                continue

            # data_block = target_byte[position+write_block_header]
            cal_checksum = zlib.crc32(target_byte[position:
                                                  position +
                                                  write_block_header +
                                                  data_block_length]) & 0xffffffff

            stored_checksum = int(target_byte[position +
                                              write_block_header +
                                              data_block_length:
                                              position +
                                              write_block_header +
                                              data_block_length +
                                              write_block_checksum].encode('hex'), 16)

            logging.debug('Thread-id-{} position: {}, write_block_header: {}, data_block_length: {}, write_block_checksum: {}'.format(_get_ident(), position, write_block_header, data_block_length, write_block_checksum))
            logging.debug('Thread-id-{} cal_checksum: {}'.format(_get_ident(), cal_checksum))
            logging.debug('Thread-id-{} stored_checksum: {}'.format(_get_ident(), stored_checksum))

            if cal_checksum != stored_checksum:
                logging.debug(
                    "Thread-id-{} Block data corrupted, {} - {} jump to next byte, current position: {}, end_position: {}"
                        .format(_get_ident(), str(cal_checksum), str(stored_checksum), position, end_position))

                position = position + 1
                continue

            calculated_chunk_id = target_byte[position + write_block_header + data_block_length + write_block_checksum:
                                              position + write_block_header + data_block_length + write_block_checksum +
                                              write_block_epoch]
            calculated_chunk_id = str(calculated_chunk_id).strip()
            logging.debug('Thread-id-{} calculated_chunk_id: {}'.format(_get_ident(), calculated_chunk_id))

            if not calculated_chunk_id:
                logging.debug('Thread-id-{} epoch corrupted, jump to next candidate byte. '.format(_get_ident()))

                position = position + write_block_header + data_block_length + write_block_checksum
                continue

            if calculated_chunk_id in self.chunkids:
                logging.debug("Thread-id-{} Found write block for chunk: {} ".format(_get_ident(), calculated_chunk_id))
                data_length = write_block_header + data_block_length + write_block_checksum + write_block_epoch
                self.write_target_block(target_byte[position+write_block_header:position+write_block_header+data_block_length],
                                        calculated_chunk_id,partition,blockBin, position, data_length)

            position = position + write_block_header + data_block_length + write_block_checksum + write_block_epoch
            logging.debug('Thread-id-{} End of loop, position: {}'.format(_get_ident(), position))

    logging.info('Thread-id-{} Candidate block done.'.format(_get_ident()))

    def do_scan(self, chunkids_file, is_force):

        if not os.path.exists(self.res_dir):
            logging.info("result dir: {} not existed, creating.".format(self.res_dir))
            os.mkdir(self.res_dir)

        with open(chunkids_file) as f:
            self.chunkids = [chunk.strip() for chunk in f.read().splitlines()]
            logging.info("Target chunkIds: {}".format(self.chunkids))

        # output_file = self.get_free_blocks_with_history()
        output_file = '/tmp/free_blocks_with_history_10.142.12.205_2019-06-20-08-10-21'
        candidate_blocks = {}
        logging.info("Scan mode is force: {}".format(is_force))
        with open(output_file) as f:
            for line in f:
                try:
                    free_block_info = json.loads(line.strip())
                    if is_force and free_block_info['chunkHistory']['chunkIdValue'] in self.chunkids:
                        block_file = '/dae/uuid-{}/{}'.format(free_block_info['partition'], free_block_info['blockBin'])
                        if block_file in candidate_blocks:
                            candidate_blocks[block_file].append(free_block_info)
                        else:
                            candidate_blocks[block_file] = [free_block_info]
                    else:
                        block_file = '/dae/uuid-{}/{}'.format(free_block_info['partition'], free_block_info['blockBin'])
                        if block_file in candidate_blocks:
                            candidate_blocks[block_file].append(free_block_info)
                        else:
                            candidate_blocks[block_file] = [free_block_info]
                except Exception as e:
                    logging.error(
                        "Hit error: {} when get candidate free blocks, trackback:{}".format(e, traceback.format_exc()))

        if len(candidate_blocks) < 1:
            logging.warn("No candidate found, exiting.")
            print "No candidate found, exiting."
            exit(100)
        print 'Total: {} candidate blocks need to pre-check.\n'.format(len(candidate_blocks))

        '''
        TODO: Can we enable the multi-threading for the following pre-checking part? 
        '''
        candidate_block = []
        for block_file in candidate_blocks.iterkeys():
            logging.debug('Pre-checking block: {}'.format(block_file))
            # with open(block_file, 'rb') as f:
            cmd = "grep -oPa '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}' %s | sort | uniq" % block_file
            chunkids_file = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=self.FNULL).communicate()[0].strip()
            tmp_chunks = chunkids_file.splitlines()
            for chunkid in self.chunkids:
                if chunkid in tmp_chunks:
                    logging.info('Found target chunkid: {} in block: {}'.format(chunkid, block_file))
                    candidate_block = candidate_block + candidate_blocks[block_file]

        if len(candidate_block) < 1:
            logging.warn("No candidate found, exiting.")
            print "No candidate found, exiting."
            exit(100)

        print 'Total: {} candidate block need to scan.\n'.format(len(candidate_block))

        if len(candidate_blocks) < 1:
            logging.warn("No candidate found, exiting.")
            print "No candidate found, exiting."
            exit(100)

        for block in candidate_block:
            block_file = '/dae/uuid-{}/{}'.format(block['partition'], block['blockBin'])
            position = int(block['offset'])
            size = int(block['size'])
            partition = block['partition']
            blockBin = block['blockBin']
            block_file_handle = open(block_file, 'rb')
            self.__do_scan(block_file_handle, position, size, partition, blockBin, block_file)
            block_file_handle.close()

        logging.info("All Done.")

    def main(self):
        print "Log file will be saved in: {}".format(self.log_file)
        logging.info("Log file will be saved in: {}".format(self.log_file))
        print 'Result will be saved in dir: {}'.format(self.res_dir)

        if self.args['action'] == 'scan':
            chunkids = self.args['filename']
            is_force = self.args['force']
            self.do_scan(chunkids, is_force)

def get_args():
    parser = argparse.ArgumentParser(description="scan the busy blocks for target chunks from disk")
    parser.add_argument('-v', '--version', help='print the Script version number', action="version",
                        version="%(prog)s v" + __version__)

    subparsers = parser.add_subparsers(help='sub-command help', dest="action")

    parser_dump = subparsers.add_parser('scan', help='start scan the busy blocks')

    parser_dump.add_argument('-f', '--filename', help='Files with List of target chunkIds', required=True)

    parser_dump.add_argument('-fo', '--force', help='force to scan all free blocks', default=False, action='store_true')

    args = parser.parse_args()

    return vars(args)

if __name__ == '__main__':
    start_time = timeit.default_timer()
    params = get_args()
    scan_busy_blocks_from_disk = ScanBusyBlocksFromDisk(params)
    scan_busy_blocks_from_disk.main()
    elapsed = int(timeit.default_timer() - start_time)
    seconds = elapsed % 60
    minutes = (elapsed - seconds) / 60
    hours = (minutes - (minutes % 60)) / 60
    days = (hours - (hours % 24)) / 24
    print '\nExecution Time:'
    if days > 0:
        hours = hours % 24
        print '{} days'.format(days),
    if hours > 0:
        minutes = minutes % 60
        print '{} hours'.format(hours),
    if minutes > 0:
        print '{} minutes'.format(minutes),

    print '{} seconds'.format(seconds)

**Comment by anarchy9388** [comment]
@MarkHe1222 

I gave you collaborator access, can you push to its own branch?
