### ISSUE TITLE
Can we add multi-threading for the pre-checking phase? since it also time consuming

### ISSUE THREAD

**Issue by MarkHe1222** [anarchy9388/scan#5]
'''
        TODO: Can we enable the multi-threading for the following pre-checking part? 
        '''
        candidate_block = []
        for block_file in candidate_blocks.iterkeys():
            logging.debug('Pre-checking block: {}'.format(block_file))
            # with open(block_file, 'rb') as f:
            cmd = "grep -oPa '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}' %s | sort | uniq" % block_file
            chunkids_file = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=self.FNULL).communicate()[0].strip()
            tmp_chunks = chunkids_file.splitlines()
            for chunkid in self.chunkids:
                if chunkid in tmp_chunks:
                    logging.info('Found target chunkid: {} in block: {}'.format(chunkid, block_file))
                    candidate_block = candidate_block + candidate_blocks[block_file]

        if len(candidate_block) < 1:
            logging.warn("No candidate found, exiting.")
            print "No candidate found, exiting."
            exit(100)

**Comment by anarchy9388** [comment]
Yeah we can use multiple processes for the greps :)
But lets wait till we have most of the logic in place first.
